### ISSUE TITLE
I got an IndexError when I used teleport

### ISSUE THREAD

**Issue by natkam** [PyThingy/roguelike#7]
I opened the teleport and I got an IndexError: list index out of range. Here's what I got:

Traceback (most recent call last):
  File "rogue.py", line 192, in <module>
    curses.wrapper(main)
  File "C:\Python34\lib\curses__init__.py", line 94, in wrapper
    return func(stdscr, _args, *_kwds)
  File "rogue.py", line 187, in main
    game.run()
  File "rogue.py", line 175, in run
    action = self.action()
  File "rogue.py", line 127, in action
    return actions.Move(self.player, self.map.tiles[y+randint(1,20)][x+randint(1,70)])
IndexError: list index out of range

**Comment by mrzechonek** [comment]
I think it might be related to teleport's location. Note how target tile is calculated: y + randint, x + randint, meaning that:
- teleport will only transport you east/south
- if it's too far to the south or east, calculated index might fall outside of the map

try something like this:

```
random_tile = random.choice(random.choice(self.map.tiles))
```

and then

```
return actions.Move(self.player, random_tile)
```
